[package]
name = "display"
version.workspace = true
authors.workspace = true
documentation.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "4.1.2", features = ["tokio"] }
mecha_display_ctl = "0.1.0"
utils ={ path = "../utils"}
